name: Maven Package

on:
  pull_request:
    branches: [main]
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: github  # must match the <id> in pom.xml distributionManagement
          settings-path: ${{ github.workspace }}

      - name: Generate settings.xml
        run: |
          echo "<settings>
                  <servers>
                    <server>
                      <id>github</id>
                      <username>${{ github.actor }}</username>
                      <password>${{ secrets.GITHUB_TOKEN }}</password>
                    </server>
                  </servers>
                </settings>" > $GITHUB_WORKSPACE/settings.xml

      - name: Build Project
        run: mvn clean install

      - name: Deploy to GitHub Packages
        run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
